/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorAuto;
import javax.swing.JOptionPane;
import modelo.Auto;

/**
 *
 * @author Domenika Delgado
 */
public class AnadirCoche extends javax.swing.JInternalFrame {

    /**
     * Creates new form Coche
     */
    String opcionMarca;
    String opcionModelo;
    String opciontipo;
    ControladorAuto controladorAuto;
    String email;
    
    public AnadirCoche(String emai) {
        initComponents();
        controladorAuto = new ControladorAuto();
        email=emai;
        //Cargamos el ComboBox
        if(controladorAuto.llenarComboBoxNombreMarca(jComboMarca)==false){
            JOptionPane.showMessageDialog(null,"Cargado valores", "Informacion", JOptionPane.INFORMATION_MESSAGE); 
        }
        
        if(controladorAuto.llenarComboBoxNombreTipo(jComboTipoCoche)==false){
            JOptionPane.showMessageDialog(null,"Cargado valores", "Informacion", JOptionPane.INFORMATION_MESSAGE); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboMarca = new javax.swing.JComboBox<>();
        comboBoxModelo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboTipoCoche = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnAnadir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtColor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setTitle("Añadir Coche");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Placa");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));
        getContentPane().add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 140, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("¿Cuál es la marca de tu coche?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("¿Qué modelo?");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jComboMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 146, -1));

        comboBoxModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxModeloActionPerformed(evt);
            }
        });
        getContentPane().add(comboBoxModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 145, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("¿Qué tipo de coche tienes?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jComboTipoCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoCocheActionPerformed(evt);
            }
        });
        getContentPane().add(jComboTipoCoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 144, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("¿De qué color es?");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        btnAnadir.setBackground(new java.awt.Color(153, 255, 255));
        btnAnadir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAnadir.setForeground(new java.awt.Color(255, 255, 255));
        btnAnadir.setText("Añadir");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 90, -1));

        btnCancelar.setBackground(new java.awt.Color(153, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, -1, -1));
        getContentPane().add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 140, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        
        opcionModelo=comboBoxModelo.getSelectedItem().toString();
        Auto auto= new Auto();
        
        auto.setId(controladorAuto.llenarId());
        auto.setPlaca(txtColor.getText());
        auto.setColor(txtColor.getText());
        auto.setEspacio(0);
        auto.setEstado('A');
        auto.setTip_aut_id_fk(controladorAuto.buscarTipo(opciontipo));
        auto.setMod_id_fk(controladorAuto.buscarModelo(opcionMarca));
        auto.setUsu_id_fk(controladorAuto.buscar(email));
        
        System.out.println("d"+auto.getMod_id_fk());
        
        if(controladorAuto.anadirAuto(auto)==true){
        JOptionPane.showMessageDialog(null,"Guardado", "Informacion", JOptionPane.INFORMATION_MESSAGE); 
        dispose();
        }
        
    }//GEN-LAST:event_btnAnadirActionPerformed

    private void jComboMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMarcaActionPerformed
        controladorAuto.vaciarComboBox(comboBoxModelo);
        opcionMarca=jComboMarca.getSelectedItem().toString();
        int a=controladorAuto.buscarIdMarca(opcionMarca);
        if(controladorAuto.llenarComboBoxNombreModelo(comboBoxModelo,a)==false){
        }
        
    }//GEN-LAST:event_jComboMarcaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jComboTipoCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoCocheActionPerformed
        opciontipo=jComboTipoCoche.getSelectedItem().toString();
    }//GEN-LAST:event_jComboTipoCocheActionPerformed

    private void comboBoxModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxModeloActionPerformed
        
    }//GEN-LAST:event_comboBoxModeloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> comboBoxModelo;
    private javax.swing.JComboBox<String> jComboMarca;
    private javax.swing.JComboBox<String> jComboTipoCoche;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
