/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorLogin;
import javax.swing.JOptionPane;

/**
 *
 * @author Domenika Delgado
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    Principal principal;
    BlaBlaCar blablacar;
    ControladorLogin controladorLogin;
    
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        controladorLogin=new ControladorLogin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        labelpassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        imagen = new javax.swing.JLabel();
        imagen1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        labelUsername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(255, 51, 51));
        labelUsername.setText("Username");
        getContentPane().add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsernameKeyPressed(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 220, -1));

        labelpassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelpassword.setForeground(new java.awt.Color(255, 51, 51));
        labelpassword.setText("Password");
        getContentPane().add(labelpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 220, -1));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login.png"))); // NOI18N
        getContentPane().add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 190, 180));

        imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login.png"))); // NOI18N
        getContentPane().add(imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyPressed
        // TODO add your handling code here:
        int codigo= evt.getKeyCode();
        if(codigo==27){
           principal = new Principal();
           setVisible(false);
           principal.setVisible(true); 
        }
        
    }//GEN-LAST:event_txtUsernameKeyPressed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        // TODO add your handling code here:
        int codigo= evt.getKeyCode();
        if(codigo==27){
           principal = new Principal();
           setVisible(false);
           principal.setVisible(true); 
        }else if(codigo==10){
            
            if(txtUsername.equals("")|| txtPassword.equals("")){
                JOptionPane.showMessageDialog(null,"Llene las celdas", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                String pasS=new String(txtPassword.getPassword());
                
                if (controladorLogin.buscarLogin(txtUsername.getText(), pasS)==true){
                       blablacar = new BlaBlaCar(controladorLogin.buscar(txtUsername.getText()),txtUsername.getText());
                       setVisible(false);
                       blablacar.setVisible(true); 
                }else{
                     JOptionPane.showMessageDialog(null,"Datos no Existen", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
           
        }
        
    }//GEN-LAST:event_txtPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel imagen1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel labelpassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
