/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Domenika Delgado
 */
public class Perfil extends javax.swing.JInternalFrame {

    
    InformacionPersonal informacionPersonal;
    Preferencia preferencia;
    ListaCoche listaCoche;
    String email;
    /**
     * Creates new form Perfil
     */
    public Perfil(String ema) {
        initComponents();
        email=ema;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnInformacionPersonal = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Profile");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Pristina", 1, 36)); // NOI18N
        jLabel1.setText("Información de Perfil");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        btnInformacionPersonal.setBackground(new java.awt.Color(255, 204, 51));
        btnInformacionPersonal.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnInformacionPersonal.setForeground(new java.awt.Color(51, 51, 51));
        btnInformacionPersonal.setText("Informacion Personal");
        btnInformacionPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacionPersonalActionPerformed(evt);
            }
        });
        getContentPane().add(btnInformacionPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 51));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Preferencias");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 170, -1));

        jButton2.setBackground(new java.awt.Color(255, 204, 51));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Coche");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 170, -1));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info.png.jpg"))); // NOI18N
        getContentPane().add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInformacionPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacionPersonalActionPerformed
        
        if(informacionPersonal == null || !informacionPersonal.isVisible()){
        informacionPersonal = new InformacionPersonal();
        BlaBlaCar.jDesktopPane1.add(informacionPersonal);
        informacionPersonal.toFront();
        informacionPersonal.setVisible(true);
        }
    }//GEN-LAST:event_btnInformacionPersonalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(preferencia == null || !preferencia.isVisible()){
        preferencia = new Preferencia(email);
        BlaBlaCar.jDesktopPane1.add(preferencia);
        preferencia.toFront();
        preferencia.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(listaCoche == null || !listaCoche.isVisible()){
        listaCoche = new ListaCoche(email);
        BlaBlaCar.jDesktopPane1.add(listaCoche);
        listaCoche.toFront();
        listaCoche.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInformacionPersonal;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
