/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorPreferencias;
import java.awt.Color;
import modelo.Preferencias;

/**
 *
 * @author alexa
 */
public class Preferencia extends javax.swing.JInternalFrame {

    /**
     * Creates new form Preferencia
     */
    ControladorPreferencias controladorPreferencias;
    Preferencias pre= new Preferencias();
    
    int habla,fumar,mascota,musica;
    int id;
    
    String email;
    public Preferencia(String ema) {
        initComponents();
        email=ema;
        controladorPreferencias = new ControladorPreferencias();
        
        pre=controladorPreferencias.buscarPreferencias(controladorPreferencias.buscarid(email));
        id=pre.getBla_usuarios_usu_id();
        switch(pre.getPre_conversacion()){
            case 0:
                botonHabla0.setBackground(Color.BLUE);
                botonHabla1.setBackground(Color.GRAY);
                botonHabla2.setBackground(Color.GRAY);
                break;
            case 1:
                botonHabla0.setBackground(Color.GRAY);
                botonHabla1.setBackground(Color.BLUE);
                botonHabla2.setBackground(Color.GRAY);
                break;
            case 2:
                botonHabla0.setBackground(Color.GRAY);
                botonHabla1.setBackground(Color.GRAY);
                botonHabla2.setBackground(Color.BLUE);
                break;
        }
        
        switch(pre.getPre_fumar()){
            case 0:
                botonfumar0.setBackground(Color.BLUE);
                botonfumar1.setBackground(Color.GRAY);
                botonfumar2.setBackground(Color.GRAY);
                break;
            case 1:
                botonfumar0.setBackground(Color.GRAY);
                botonfumar1.setBackground(Color.BLUE);
                botonfumar2.setBackground(Color.GRAY);
                break;
            case 2:
                botonfumar0.setBackground(Color.GRAY);
                botonfumar1.setBackground(Color.GRAY);
                botonfumar2.setBackground(Color.BLUE);
                break;
        }

        switch(pre.getPre_mascota()){
            case 0:
                botonMascota0.setBackground(Color.BLUE);
                botonMascota1.setBackground(Color.GRAY);
                botonMascota2.setBackground(Color.GRAY);
                break;
            case 1:
                botonMascota0.setBackground(Color.GRAY);
                botonMascota1.setBackground(Color.BLUE);
                botonMascota2.setBackground(Color.GRAY);
                break;
            case 2:
                botonMascota0.setBackground(Color.GRAY);
                botonMascota1.setBackground(Color.GRAY);
                botonMascota2.setBackground(Color.BLUE);
                break;
        }
        
        switch(pre.getPre_musica()){
            case 0:
                botonMusica0.setBackground(Color.BLUE);
                botonMusica1.setBackground(Color.GRAY);
                botonMusica2.setBackground(Color.GRAY);
                break;
            case 1:
                botonMusica0.setBackground(Color.GRAY);
                botonMusica1.setBackground(Color.BLUE);
                botonMusica2.setBackground(Color.GRAY);
                break;
            case 2:
                botonMusica0.setBackground(Color.GRAY);
                botonMusica1.setBackground(Color.GRAY);
                botonMusica2.setBackground(Color.BLUE);
                break;
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonHabla0 = new javax.swing.JButton();
        botonHabla1 = new javax.swing.JButton();
        botonfumar1 = new javax.swing.JButton();
        botonfumar0 = new javax.swing.JButton();
        botonHabla2 = new javax.swing.JButton();
        botonMascota1 = new javax.swing.JButton();
        botonMusica0 = new javax.swing.JButton();
        botonMascota2 = new javax.swing.JButton();
        botonfumar2 = new javax.swing.JButton();
        botonMascota0 = new javax.swing.JButton();
        botonMusica1 = new javax.swing.JButton();
        botonMusica2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Preferencias");

        jLabel1.setText("Conversación:");

        jLabel2.setText("Fumar en el Coche:");

        jLabel3.setText("Mascota:");

        jLabel4.setText("Música:");

        botonHabla0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hablar0.png"))); // NOI18N
        botonHabla0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHabla0ActionPerformed(evt);
            }
        });

        botonHabla1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hablar1.png"))); // NOI18N
        botonHabla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHabla1ActionPerformed(evt);
            }
        });

        botonfumar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fumar1.png"))); // NOI18N
        botonfumar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonfumar1ActionPerformed(evt);
            }
        });

        botonfumar0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fumar0.png"))); // NOI18N
        botonfumar0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonfumar0ActionPerformed(evt);
            }
        });

        botonHabla2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hablar2.png"))); // NOI18N
        botonHabla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHabla2ActionPerformed(evt);
            }
        });

        botonMascota1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mascota1.png"))); // NOI18N
        botonMascota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMascota1ActionPerformed(evt);
            }
        });

        botonMusica0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/musica0.png"))); // NOI18N
        botonMusica0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMusica0ActionPerformed(evt);
            }
        });

        botonMascota2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mascota2.png"))); // NOI18N
        botonMascota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMascota2ActionPerformed(evt);
            }
        });

        botonfumar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fumar2.png"))); // NOI18N
        botonfumar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonfumar2ActionPerformed(evt);
            }
        });

        botonMascota0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mascota0.png"))); // NOI18N
        botonMascota0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMascota0ActionPerformed(evt);
            }
        });

        botonMusica1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/musica1.png"))); // NOI18N
        botonMusica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMusica1ActionPerformed(evt);
            }
        });

        botonMusica2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/musica2.png"))); // NOI18N
        botonMusica2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMusica2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jButton1.setText("Validar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonHabla0, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonMusica0, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonfumar0, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonMascota0, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonfumar1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonHabla1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMascota1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMusica1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonMascota2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonfumar2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonHabla2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMusica2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(243, 243, 243))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonHabla0, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonHabla1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonHabla2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonfumar0, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonfumar1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonfumar2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonMascota1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(botonMusica1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonMascota2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonMusica2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonMascota0, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonMusica0, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonHabla0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHabla0ActionPerformed
        botonHabla0.setBackground(Color.BLUE);
        botonHabla1.setBackground(Color.GRAY);
        botonHabla2.setBackground(Color.GRAY);
        habla=0;
    }//GEN-LAST:event_botonHabla0ActionPerformed

    private void botonHabla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHabla1ActionPerformed
        // TODO add your handling code here:
        botonHabla0.setBackground(Color.GRAY);
        botonHabla1.setBackground(Color.BLUE);
        botonHabla2.setBackground(Color.GRAY);
        habla=1;
    }//GEN-LAST:event_botonHabla1ActionPerformed

    private void botonHabla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHabla2ActionPerformed
        // TODO add your handling code here:
        botonHabla0.setBackground(Color.GRAY);
        botonHabla1.setBackground(Color.GRAY);
        botonHabla2.setBackground(Color.BLUE);
        habla=2;
    }//GEN-LAST:event_botonHabla2ActionPerformed

    private void botonfumar0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonfumar0ActionPerformed
        botonfumar0.setBackground(Color.BLUE);
        botonfumar1.setBackground(Color.GRAY);
        botonfumar2.setBackground(Color.GRAY);
        fumar=0;
    }//GEN-LAST:event_botonfumar0ActionPerformed

    private void botonfumar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonfumar1ActionPerformed
        // TODO add your handling code here:
        botonfumar0.setBackground(Color.GRAY);
        botonfumar1.setBackground(Color.BLUE);
        botonfumar2.setBackground(Color.GRAY);
        fumar=1;
    }//GEN-LAST:event_botonfumar1ActionPerformed

    private void botonfumar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonfumar2ActionPerformed
        // TODO add your handling code here:
        botonfumar0.setBackground(Color.GRAY);
        botonfumar1.setBackground(Color.GRAY);
        botonfumar2.setBackground(Color.BLUE);
        fumar=2;
    }//GEN-LAST:event_botonfumar2ActionPerformed

    private void botonMascota0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMascota0ActionPerformed
        botonMascota0.setBackground(Color.BLUE);
        botonMascota1.setBackground(Color.GRAY);
        botonMascota2.setBackground(Color.GRAY);
        mascota=0;
    }//GEN-LAST:event_botonMascota0ActionPerformed

    private void botonMascota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMascota1ActionPerformed
        // TODO add your handling code here:
        botonMascota0.setBackground(Color.GRAY);
        botonMascota1.setBackground(Color.BLUE);
        botonMascota2.setBackground(Color.GRAY);
        mascota=1;
    }//GEN-LAST:event_botonMascota1ActionPerformed

    private void botonMascota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMascota2ActionPerformed
        // TODO add your handling code here:
        botonMascota0.setBackground(Color.GRAY);
        botonMascota1.setBackground(Color.GRAY);
        botonMascota2.setBackground(Color.BLUE);
        mascota=2;
    }//GEN-LAST:event_botonMascota2ActionPerformed

    private void botonMusica0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMusica0ActionPerformed
        // TODO add your handling code here:
        botonMusica0.setBackground(Color.BLUE);
        botonMusica1.setBackground(Color.GRAY);
        botonMusica2.setBackground(Color.GRAY);
        musica=0;
    }//GEN-LAST:event_botonMusica0ActionPerformed

    private void botonMusica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMusica1ActionPerformed
        // TODO add your handling code here:
        botonMusica0.setBackground(Color.GRAY);
        botonMusica1.setBackground(Color.BLUE);
        botonMusica2.setBackground(Color.GRAY);
        musica=1;
    }//GEN-LAST:event_botonMusica1ActionPerformed

    private void botonMusica2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMusica2ActionPerformed
        // TODO add your handling code here:
        botonMusica0.setBackground(Color.GRAY);
        botonMusica1.setBackground(Color.GRAY);
        botonMusica2.setBackground(Color.BLUE);
        musica=2;
    }//GEN-LAST:event_botonMusica2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controladorPreferencias.actualizarAuto(habla, fumar, mascota, musica, id);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonHabla0;
    private javax.swing.JButton botonHabla1;
    private javax.swing.JButton botonHabla2;
    private javax.swing.JButton botonMascota0;
    private javax.swing.JButton botonMascota1;
    private javax.swing.JButton botonMascota2;
    private javax.swing.JButton botonMusica0;
    private javax.swing.JButton botonMusica1;
    private javax.swing.JButton botonMusica2;
    private javax.swing.JButton botonfumar0;
    private javax.swing.JButton botonfumar1;
    private javax.swing.JButton botonfumar2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
